apiVersion: v1
kind: Secret
metadata:
  name: rhoai-api-keys
  namespace: openshift-lightspeed
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: openshift-lightspeed
    app.kubernetes.io/part-of: openshift-lightspeed
type: Opaque
stringData:
  apitoken: "dummy-token-for-no-auth"
