apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-backend-stable-services.yaml
  - 02-serviceaccount.yaml
  - 03-pvcs.yaml
  - 04-configmap-router.yaml
  - 05-configmap-envoy.yaml
  - 06-deployment.yaml
  - 07-service.yaml
  - 08-route.yaml
