apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
  labels:
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/instance: default-dsc
    app.kubernetes.io/part-of: rhods-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rhods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  components:
    dashboard:
      managementState: Managed
    aipipelines:
      managementState: Managed
    kserve:
      managementState: Managed
      rawDeploymentServiceConfig: Headless
      nim:
        managementState: Managed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    feastoperator:
      managementState: Removed
    trustyai:
      managementState: Managed
    ray:
      managementState: Managed
    # In v2, kueue only allows Unmanaged or Removed (Managed no longer supported)
    kueue:
      managementState: Unmanaged
    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks
    llamastackoperator:
      managementState: Managed
    trainingoperator:
      managementState: Managed
    trainer:
      managementState: Managed
