apiVersion: v1
kind: ServiceAccount
metadata:
  name: fix-cdi-hooks
  namespace: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "9"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fix-cdi-hooks
  annotations:
    argocd.argoproj.io/sync-wave: "9"
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["nodes/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fix-cdi-hooks
  annotations:
    argocd.argoproj.io/sync-wave: "9"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fix-cdi-hooks
subjects:
- kind: ServiceAccount
  name: fix-cdi-hooks
  namespace: nvidia-gpu-operator
---
# Grant privileged SCC access for oc debug node command
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fix-cdi-hooks-scc
  annotations:
    argocd.argoproj.io/sync-wave: "9"
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fix-cdi-hooks-scc
  annotations:
    argocd.argoproj.io/sync-wave: "9"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fix-cdi-hooks-scc
subjects:
- kind: ServiceAccount
  name: fix-cdi-hooks
  namespace: nvidia-gpu-operator

