apiVersion: batch/v1
kind: CronJob
metadata:
  name: fix-cdi-hooks
  namespace: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  # Run every 5 minutes to keep CDI specs fixed
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: fix-cdi-hooks
        spec:
          serviceAccountName: fix-cdi-hooks
          restartPolicy: OnFailure
          containers:
          - name: fix-cdi
            image: quay.io/openshift/origin-cli:latest
            command:
            - /bin/bash
            - -c
            - |
              set +e  # Don't exit on error, continue processing all nodes
              echo "============================================================"
              echo "Periodic CDI Hook Fix (CronJob)"
              echo "============================================================"
              echo "Timestamp: $(date)"
              echo ""
              
              # Get all nodes with GPUs
              GPU_NODES=$(oc get nodes -l nvidia.com/gpu.present=true -o jsonpath='{.items[*].metadata.name}' 2>/dev/null || echo "")
              
              if [ -z "$GPU_NODES" ]; then
                echo "No GPU nodes found, exiting..."
                exit 0
              fi
              
              echo "Found GPU nodes: $GPU_NODES"
              echo ""
              
              # Pre-encoded Python script (base64) - improved version that handles already-fixed cases
              PYTHON_SCRIPT_B64="aW1wb3J0IGpzb24KaW1wb3J0IHN5cwoKY2RpX2ZpbGUgPSAiL3Zhci9ydW4vY2RpL2s4cy5kZXZpY2UtcGx1Z2luLm52aWRpYS5jb20tZ3B1Lmpzb24iCgp0cnk6CiAgICB3aXRoIG9wZW4oY2RpX2ZpbGUsICJyIikgYXMgZjoKICAgICAgICBkYXRhID0ganNvbi5sb2FkKGYpCiAgICAKICAgICMgUmVtb3ZlIGFsbCBob29rcyBhbmQgc2V0IGVudiB2YXJpYWJsZXMKICAgIGlmICJjb250YWluZXJFZGl0cyIgaW4gZGF0YToKICAgICAgICBob29rc19jb3VudCA9IGxlbihkYXRhWyJjb250YWluZXJFZGl0cyJdLmdldCgiaG9va3MiLCBbXSkpCiAgICAgICAgbmVlZHNfZml4ID0gRmFsc2UKICAgICAgICAKICAgICAgICAjIENoZWNrIGlmIGhvb2tzIGV4aXN0IGFuZCBuZWVkIHRvIGJlIHJlbW92ZWQKICAgICAgICBpZiBob29rc19jb3VudCA+IDA6CiAgICAgICAgICAgIHByaW50KGYiICAgIFJlbW92aW5nIHtob29rc19jb3VudH0gaG9va3MuLi4iKQogICAgICAgICAgICBkYXRhWyJjb250YWluZXJFZGl0cyJdWyJob29rcyJdID0gW10KICAgICAgICAgICAgbmVlZHNfZml4ID0gVHJ1ZQogICAgICAgIAogICAgICAgICMgU2V0IGVudmlyb25tZW50IHZhcmlhYmxlcyAoYWx3YXlzIGVuc3VyZSBjb3JyZWN0IHZhbHVlcykKICAgICAgICBlbnZfbGlzdCA9IGRhdGFbImNvbnRhaW5lckVkaXRzIl0uZ2V0KCJlbnYiLCBbXSkKICAgICAgICBleGlzdGluZ19lbnYgPSBbZSBmb3IgZSBpbiBlbnZfbGlzdCBpZiAiTlZJRElBXyIgbm90IGluIGVdCiAgICAgICAgZGF0YVsiY29udGFpbmVyRWRpdHMiXVsiZW52Il0gPSBleGlzdGluZ19lbnYgKyBbCiAgICAgICAgICAgICJOVklESUFfQ1RLX0xJQkNVREFfRElSPS91c3IvbGliNjQiLAogICAgICAgICAgICAiTlZJRElBX1ZJU0lCTEVfREVWSUNFUz1hbGwiCiAgICAgICAgXQogICAgICAgIAogICAgICAgICMgT25seSB3cml0ZSBpZiBzb21ldGhpbmcgY2hhbmdlZAogICAgICAgIGlmIG5lZWRzX2ZpeDoKICAgICAgICAgICAgd2l0aCBvcGVuKGNkaV9maWxlLCAidyIpIGFzIGY6CiAgICAgICAgICAgICAgICBqc29uLmR1bXAoZGF0YSwgZiwgaW5kZW50PTIpCiAgICAgICAgICAgIHByaW50KCIgICAg4pyTIENESSBzcGVjIGZpeGVkIHN1Y2Nlc3NmdWxseSIpCiAgICAgICAgZWxzZToKICAgICAgICAgICAgcHJpbnQoIiAgICDinJMgQ0RJIHNwZWMgYWxyZWFkeSBjb3JyZWN0IChubyBmaXggbmVlZGVkKSIpCiAgICAKZXhjZXB0IEZpbGVOb3RGb3VuZEVycm9yOgogICAgcHJpbnQoIiAgICDimqAgQ0RJIHNwZWMgZmlsZSBub3QgZm91bmQiKQogICAgc3lzLmV4aXQoMCkKZXhjZXB0IGpzb24uSlNPTkRlY29kZUVycm9yIGFzIGU6CiAgICBwcmludChmIiAgICDinJcgRXJyb3IgcGFyc2luZyBKU09OOiB7ZX0iKQogICAgc3lzLmV4aXQoMSkKZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgcHJpbnQoZiIgICAg4pyXIEVycm9yOiB7ZX0iKQogICAgc3lzLmV4aXQoMSkK"
              
              FIXED_COUNT=0
              ALREADY_FIXED_COUNT=0
              FAILED_COUNT=0
              SKIPPED_COUNT=0
              
              for NODE in $GPU_NODES; do
                echo "Processing node: $NODE"
                
                RESULT=$(oc debug node/$NODE -- chroot /host /bin/bash -c "
                  set +e
                  CDI_SPEC_FILE=\"/var/run/cdi/k8s.device-plugin.nvidia.com-gpu.json\"
                  
                  # Check if file exists
                  if [ ! -f \"\$CDI_SPEC_FILE\" ]; then
                    echo 'SKIP:CDI spec file not found'
                    exit 0
                  fi
                  
                  # Check if Python and base64 are available
                  if ! command -v python3 &> /dev/null; then
                    echo 'ERROR:python3 not found'
                    exit 1
                  fi
                  
                  if ! command -v base64 &> /dev/null; then
                    echo 'ERROR:base64 not found'
                    exit 1
                  fi
                  
                  # Run the Python fix script
                  echo '$PYTHON_SCRIPT_B64' | base64 -d | python3 2>&1
                  EXIT_CODE=\$?
                  
                  if [ \$EXIT_CODE -eq 0 ]; then
                    exit 0
                  else
                    exit 1
                  fi
                " 2>&1)
                
                EXIT_CODE=$?
                
                if echo "$RESULT" | grep -q "CDI spec fixed successfully"; then
                  FIXED_COUNT=$((FIXED_COUNT + 1))
                  echo "  ✓ Fixed (removed hooks)"
                elif echo "$RESULT" | grep -q "CDI spec already correct"; then
                  ALREADY_FIXED_COUNT=$((ALREADY_FIXED_COUNT + 1))
                  echo "  ✓ Already correct (no hooks)"
                elif echo "$RESULT" | grep -q "SKIP:"; then
                  SKIPPED_COUNT=$((SKIPPED_COUNT + 1))
                  echo "  ⚠ $(echo "$RESULT" | grep "SKIP:" | cut -d: -f2-)"
                elif [ $EXIT_CODE -ne 0 ]; then
                  FAILED_COUNT=$((FAILED_COUNT + 1))
                  echo "  ✗ Failed: $(echo "$RESULT" | tail -1)"
                else
                  # Success but no clear message
                  FIXED_COUNT=$((FIXED_COUNT + 1))
                  echo "  ✓ Fixed"
                fi
                echo ""
              done
              
              echo "============================================================"
              echo "Summary:"
              echo "  Fixed: $FIXED_COUNT"
              echo "  Already correct: $ALREADY_FIXED_COUNT"
              echo "  Skipped: $SKIPPED_COUNT"
              echo "  Failed: $FAILED_COUNT"
              echo "============================================================"
              
              # Exit with error only if all nodes failed
              if [ $FAILED_COUNT -gt 0 ] && [ $FIXED_COUNT -eq 0 ] && [ $ALREADY_FIXED_COUNT -eq 0 ]; then
                exit 1
              fi
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi

