apiVersion: batch/v1
kind: Job
metadata:
  name: fix-cdi-hooks
  namespace: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: fix-cdi-hooks
    spec:
      serviceAccountName: fix-cdi-hooks
      restartPolicy: OnFailure
      containers:
      - name: fix-cdi
        image: quay.io/openshift/origin-cli:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "============================================================"
          echo "Fixing CDI Hook Issues on All GPU Nodes"
          echo "============================================================"
          echo ""
          
          # Wait for GPU operator to be ready (check multiple daemonsets)
          echo "1. Waiting for NVIDIA GPU Operator to be ready..."
          MAX_WAIT=600
          ELAPSED=0
          while [ $ELAPSED -lt $MAX_WAIT ]; do
            # Check if any GPU operator daemonset exists and has pods
            DS_READY=false
            for DS_NAME in nvidia-container-toolkit-daemonset nvidia-container-toolkit; do
              DS_STATUS=$(oc get daemonset -n nvidia-gpu-operator $DS_NAME -o jsonpath='{.status.numberReady}/{.status.desiredNumberScheduled}' 2>/dev/null || echo "0/0")
              if [ "$DS_STATUS" != "0/0" ] && [ "$DS_STATUS" != "" ]; then
                READY=$(echo $DS_STATUS | cut -d'/' -f1)
                DESIRED=$(echo $DS_STATUS | cut -d'/' -f2)
                if [ "$READY" -gt 0 ] && [ "$READY" -eq "$DESIRED" ] 2>/dev/null; then
                  echo "   ✓ GPU Operator daemonset $DS_NAME is ready ($DS_STATUS)"
                  DS_READY=true
                  break
                elif [ "$READY" -gt 0 ]; then
                  echo "   GPU Operator daemonset $DS_NAME is partially ready ($DS_STATUS), continuing..."
                  DS_READY=true
                  break
                fi
              fi
            done
            
            # Also check if CDI spec files already exist (operator might be ready but daemonset check failed)
            if [ "$DS_READY" = "false" ]; then
              GPU_NODES_CHECK=$(oc get nodes -l nvidia.com/gpu.present=true -o jsonpath='{.items[*].metadata.name}' 2>/dev/null || echo "")
              if [ -n "$GPU_NODES_CHECK" ]; then
                # Check if CDI spec exists on at least one node
                for CHECK_NODE in $GPU_NODES_CHECK; do
                  if oc debug node/$CHECK_NODE -- chroot /host test -f /var/run/cdi/k8s.device-plugin.nvidia.com-gpu.json 2>/dev/null; then
                    echo "   ✓ CDI spec file found on node $CHECK_NODE, GPU operator appears ready"
                    DS_READY=true
                    break
                  fi
                done
              fi
            fi
            
            if [ "$DS_READY" = "true" ]; then
              break
            fi
            
            echo "   Waiting for GPU Operator... ($ELAPSED/$MAX_WAIT seconds)"
            sleep 10
            ELAPSED=$((ELAPSED + 10))
          done
          
          if [ $ELAPSED -ge $MAX_WAIT ]; then
            echo "   ⚠ WARNING: GPU Operator may not be fully ready, but continuing anyway..."
          fi
          
          # Wait a bit more for CDI specs to be generated on all nodes
          echo ""
          echo "2. Waiting for CDI specs to be generated..."
          sleep 20
          
          # Get all nodes with GPUs
          echo ""
          echo "3. Finding nodes with GPUs..."
          GPU_NODES=$(oc get nodes -l nvidia.com/gpu.present=true -o jsonpath='{.items[*].metadata.name}' 2>/dev/null || echo "")
          
          if [ -z "$GPU_NODES" ]; then
            echo "   Checking all nodes for GPU labels..."
            GPU_NODES=$(oc get nodes -o jsonpath='{.items[*].metadata.name}')
          fi
          
          if [ -z "$GPU_NODES" ]; then
            echo "   ERROR: No nodes found!"
            exit 1
          fi
          
          echo "   Found nodes: $GPU_NODES"
          echo ""
          
          # Fix CDI spec on each node using oc debug
          FIXED_COUNT=0
          FAILED_COUNT=0
          
          for NODE in $GPU_NODES; do
            echo "4. Fixing CDI spec on node: $NODE"
            
            # Pre-encoded Python script (base64) to avoid YAML parsing issues with heredocs
            PYTHON_SCRIPT_B64="aW1wb3J0IGpzb24KaW1wb3J0IHN5cwogCmNkaV9maWxlID0gIi92YXIvcnVuL2NkaS9rOHMuZGV2aWNlLXBsdWdpbi5udmlkaWEuY29tL2dwdS5qc29uIgogCnRyeToKICAgIHdpdGggb3BlbihjZGlfZmlsZSwgInIiKSBhcyBmOgogICAgICAgIGRhdGEgPSBqc29uLmxvYWQoZikKICAgIAogICAgIyBSZW1vdmUgYWxsIGhvb2tzCiAgICBpZiAiY29udGFpbmVyRWRpdHMiIGluIGRhdGE6CiAgICAgICAgaWYgImhvb2tzIiBpbiBkYXRhWyJjb250YWluZXJFZGl0cyJdOgogICAgICAgICAgICBwcmludChmIiAgICBSZW1vdmluZyB7bGVuKGRhdGFbJ2NvbnRhaW5lckVkaXRzJ11bJ2hvb2tzJ10pfSBob29rcy4uLiIpCiAgICAgICAgICAgIGRhdGFbImNvbnRhaW5lckVkaXRzIl1bImhvb2tzIl0gPSBbXQogICAgICAgIAogICAgICAgICMgU2V0IGVudmlyb25tZW50IHZhcmlhYmxlcwogICAgICAgIGRhdGFbImNvbnRhaW5lckVkaXRzIl1bImVudiJdID0gWwogICAgICAgICAgICAiTlZJRElBX0NUS19MSUJDVURBX0RJUj0vdXNyL2xpYjY0IiwKICAgICAgICAgICAgIk5WSURJQV9WSVNJQkxFX0RFVklDRVM9YWxsIgogICAgICAgIF0KICAgICAgICBwcmludCgiICAg4oiSIFNldCBOVklESUFfVklTSUJMRV9ERVZJQ0VTPWFsbCIpCiAgICAKICAgICMgV3JpdGUgdGhlIGZpeGVkIHNwZWMKICAgIHdpdGggb3BlbihjZGlfZmlsZSwgInciKSBhcyBmOgogICAgICAgIGpzb24uZHVtcChkYXRhLCBmLCBpbmRlbnQ9MikKICAgIAogICAgcHJpbnQoIiAgIOKIkiBDREkgc3BlYyBmaXhlZCBzdWNjZXNzZnVsbHkiKQogICAgCmV4Y2VwdCBGaWxlTm90Rm91bmRFcnJvcjoKICAgIHByaW50KCIgICDwn5KPIENESSBzcGVjIGZpbGUgbm90IGZvdW5kIikKICAgIHN5cy5leGl0KDApCmV4Y2VwdCBqc29uLkpTT05EZWNvZGVFcnJvciBhcyBlOgogICAgcHJpbnQoZiIgICDiiJMgRXJyb3IgcGFyc2luZyBKU09OOiB7ZX0iKQogICAgc3lzLmV4aXQoMSkKZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgcHJpbnQoZiIgICDiiJMgRXJyb3I6IHtlfSIpCiAgICBzeXMuZXhpdCgxKQ=="
            
            # Try to fix the CDI spec on this node
            if oc debug node/$NODE -- chroot /host /bin/bash -c "
              set -e
              CDI_SPEC_FILE=\"/var/run/cdi/k8s.device-plugin.nvidia.com-gpu.json\"
              
              # Check if file exists
              if [ ! -f \"\$CDI_SPEC_FILE\" ]; then
                echo '   ⚠ CDI spec file not found, skipping...'
                exit 0
              fi
              
              # Check if Python is available
              if ! command -v python3 &> /dev/null; then
                echo '   ✗ ERROR: python3 not found on node'
                exit 1
              fi
              
              # Check if base64 is available
              if ! command -v base64 &> /dev/null; then
                echo '   ✗ ERROR: base64 not found on node'
                exit 1
              fi
              
              # Backup the original file
              if [ ! -f \"\${CDI_SPEC_FILE}.backup\" ]; then
                cp \"\$CDI_SPEC_FILE\" \"\${CDI_SPEC_FILE}.backup\" || {
                  echo '   ✗ ERROR: Failed to create backup'
                  exit 1
                }
                echo '   ✓ Created backup'
              else
                echo '   ✓ Backup already exists'
              fi
              
              # Decode and run Python script
              echo '$PYTHON_SCRIPT_B64' | base64 -d | python3 || {
                echo '   ✗ ERROR: Failed to decode or execute Python script'
                exit 1
              }
            " 2>&1; then
              FIXED_COUNT=$((FIXED_COUNT + 1))
              echo "   ✓ Successfully fixed CDI spec on node $NODE"
            else
              FAILED_COUNT=$((FAILED_COUNT + 1))
              echo "   ✗ Failed to fix CDI spec on node $NODE (check logs above for details)"
            fi
            
            echo ""
          done
          
          echo "============================================================"
          echo "CDI Hook Fix Complete"
          echo "============================================================"
          echo "Nodes fixed: $FIXED_COUNT"
          echo "Nodes failed: $FAILED_COUNT"
          echo ""
          
          if [ $FAILED_COUNT -gt 0 ]; then
            echo "WARNING: Some nodes failed to fix."
            exit 1
          fi
          
          echo "✓ All nodes fixed successfully!"
          echo ""
          echo "Note: The CDI spec files may be regenerated by the container-toolkit"
          echo "daemonset. If the issue persists, restart the daemonset."
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

