apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gpu-operatorgroup
  namespace: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - nvidia-gpu-operator
