apiVersion: v1
kind: Namespace
metadata:
  name: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
  namespace: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  observability:
    enable: true
