kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  namespace: developer-hub
data:
  app-config-rhdh.yaml: |
    app:
      title: My Red Hat Developer Hub
baseUrl: https://developer-hub-developer-hub.apps.rosa.i6x3z5p5a2r0i4l.7ued.p3.openshiftapps.com/
