apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdh-github-enabled
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: developer-hub
  source:
    repoURL: https://charts.openshift.io/
    chart: redhat-developer-hub
    targetRevision: ">=1.0.0"
    helm:
      releaseName: developer-hub
      values: |
        global:
          clusterRouterBase: apps.rosa.i6x3z5p5a2r0i4l.7ued.p3.openshiftapps.com
          auth:
            backend:
              enabled: true

        appConfig:
          app:
            baseUrl: https://developer-hub-developer-hub.apps.rosa.i6x3z5p5a2r0i4l.7ued.p3.openshiftapps.com
          backend:
            baseUrl: https://developer-hub-developer-hub.apps.rosa.i6x3z5p5a2r0i4l.7ued.p3.openshiftapps.com
          auth:
            allowGuestAccess: true
            environment: production
            providers:
              github:
                development:
                  clientId: "${GITHUB_CLIENT_ID}"
                  clientSecret: "${GITHUB_CLIENT_SECRET}"
                  signIn:
                    resolvers:
                      - resolver: usernameMatchingUserEntityName
                        dangerouslyAllowSignInWithoutUserInCatalog: true
          integrations:
            github:
              - host: github.com
                token: "${GITHUB_TOKEN}"

        dynamic:
          includes:
            - dynamic-plugins.default.yaml
          plugins:
            - disabled: false
              package: "@redhat/backstage-plugin-auth-backend-module-github-dynamic"
            - disabled: false
              package: "./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
