kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
  namespace: developer-hub #project-namespace
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      # to be used for software template creation within GitHub (with default/basic list of scaffolding actions)
      # to be used for repository scanning within GitHub (i.e., auto import of GitHub repositories in the catalog section of Dev Hub)
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic
        disabled: false
      # enables GitHub actions for the software templates (e.g., publish:github)
      - package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
        disabled: false
      - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org'
        disabled: false
