apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: developer-hub-operator-group
  namespace: rhdh-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: developer-hub-operator-group
  namespace: developer-hub
spec:
  targetNamespaces:
    - developer-hub
