kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secrets
  namespace: developer-hub #project-namespace
stringData:
  BACKEND_SECRET: averysecretpassword
  basedomain: apps.rosa.i6x3z5p5a2r0i4l.7ued.p3.openshiftapps.com # TODO change this to your domain
  baseUrl: https://backstage-developer-hub-developer-hub.apps.rosa.i6x3z5p5a2r0i4l.7ued.p3.openshiftapps.com/ # TODO change this to your domain!!!
type: Opaque
