kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secrets-github-credentials
  namespace: developer-hub #project-namespace
stringData:
  RHDH_GITHUB_ORGANIZATION: "sgaikwadorg" # TODO complete me
  RHDH_GITHUB_APP_ID: "1865817"
  RHDH_GITHUB_APP_CLIENT_ID: "Iv23lizgwh4axjB8gxLB" 
  RHDH_GITHUB_APP_CLIENT_SECRET: "da1a4cc2f5c1edf9129cf1cc5057a836b73f5e03" 
  RHDH_GITHUB_APP_PRIVATE_KEY: |
    -----END RSA PRIVATE KEY-----
type: Opaque
