kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secrets-github-credentials
  namespace: demo-project #project-namespace
stringData:
  RHDH_GITHUB_ORGANIZATION: "sgaikwadorg"
  RHDH_GITHUB_APP_ID: "2120353"
  RHDH_GITHUB_APP_CLIENT_ID: "Iv23liN72iM1mNgkTU24" 
  RHDH_GITHUB_APP_CLIENT_SECRET: "52c9ad6061792d9586a64b998e24e3c2c1771dd0" 
  RHDH_GITHUB_APP_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAz//MBTC5BZETsQRUZvl+EAPxFMzp/Yhw2dpWZQeYM/9XBlsN
    l8q/lbibctC2BZmf1m7wl+blM0oF9fiNKC/yk/FEkfZ66j9xhKm649sN7PZ2IqTg
    7WqTzkvLTyVwYnskwMSX1Hkg+RmNmDUXA9Id6suKj8AGPKnBArrJwkNuedHOWiMA
    83qXwlRSvXbap0pqAjM2+mJ6MYnWhp45oEyn10a3RwMdWdIAgCvh2V9+JJCama0H
    I3EjlTz6XUu+rIOiyUfo6qLv3UPizfsbyLvHBT0FXEFzAMnmboKi2i0DINiolMMw
    LRVzcquQyq7gC7akbkBXO6OWhN10Fb1RWUMezwIDAQABAoIBAFADi/13J8XfcF7J
    VpqiYX9RtN0WkvDoGtmDZ3bH/CIMmPKl9k2tPhQfhxUc+tiep2E7HiyhMwyO7koY
    Cl0qTLvitUkdM12HeGjbTjy3GN1OVlWvbaOHO0LB330b3ubTjmjld67RxgBtdw3V
    ZnweyUl4cV4pNX0CpHAjYNftTsNnY68LnXlzgnbfuDi+ETz4KlYOS7VBvOeeoR1Q
    /OO4/F6Z1ltrO2PogZItXOd6+jzND8mNXebxifxgIxZKhybS4pUt4yQZgoqO4UBP
    PdpRjE0tC5JjjG+wPQ8YxjnbonMN+OcWwuWqj1Sh1YMnZubLE96RPzAMNI8flKJR
    iQ96YjkCgYEA8TKestdXTMzZia5t2vjCzEfIfLXN8YBOsoDYEawbnk162UXS6QrI
    OsXOq0XPNjzmvOPpELarDN4DFy7t2GLEbazrS2Tfh9UaBAw3+okEKPQrH60UNhe7
    Kjkf+aLzR5KvDYhrATRbWKl0TlTrttmxV+XrHmo6NphTH2wu41NKfzUCgYEA3MOb
    C6OjELCM5lGX+LH6Za8zPJztoEmKQWt34niQcjPrWyn2RA5/nkghAe2P9XRMKpeV
    2OnRyYYMMDpC6kPWM+wNki4n02xNC+vYxvYazF+CIp2mMAMTgAfgImad9mxF+im0
    NkdBc4hZOWmjlJsGyO+7oWoZCbNUYiX0d2p5UnMCgYAEaLZ58nHIF56KY8PiUtXM
    wisqDHC9T2kg3jYU7J58oFH0ktAuLmJGoMMMYnRNO4PERC5Ife5Wh+BqlhMG95c7
    ogOTFz72zrBxDoAfdk27Ket34sQR0RE8zlqFR7NGxamph6rdFMXusvpLTEYay5Pw
    VWWc4rg5s0MhueqJgUZFWQKBgATnk5o+mHDWe0ripS2xRo7bxZejJORaveeWK6Os
    agkffisYU5BPgiZSE+mnDXu2ibqog3u+Nhr0D3FC2hm6SBf/No342Imp7kxFgRtq
    fE3uEUYTmo2Wg+hkRGZ/QSMoZKWaJ5bNHncioFjWL/wtNYlhShnb8ZJ1mXpUvYmp
    o+hhAoGAaQsqc3HxNgosah5V/ZaTP+FWfyTCfE2wEUfQtM65MW5IoelQSptxHGyO
    dQWVUgDgbrBVbIcqoYrrrFzQWGJH8Cjp8CsEWaXQMlEFkw2vEp8QClggEO/x5BqX
    qWoaubvYffvfBCVoEHzks4sbAekg93qgVGUVW4oELo+foiDEENw=
    -----END RSA PRIVATE KEY-----
type: Opaque
