# creats a 1 pod deployment for the cluster-health-analyzer
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cluster-health-analyzer-mcp
  name: cluster-health-analyzer-mcp
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cluster-health-analyzer-mcp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cluster-health-analyzer-mcp
    spec:
      serviceAccountName: cluster-health-analyzer-mcp-thanos-querier
      automountServiceAccountToken: true
      containers:
      - name: cluster-health-mcp-server
        image: "quay.io/openshiftanalytics/cluster-health-analyzer:mcp-dev-preview"
        imagePullPolicy: Always
        args:
          - mcp
        env:
          - name: PROM_URL
            value: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091/"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8085
          name: mcp
        terminationMessagePolicy: FallbackToLogsOnError
