apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cluster-health-analyzer-mcp
  name: cluster-health-mcp-server
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ports:
  - name: mcp
    port: 8085
    targetPort: mcp
  selector:
    app.kubernetes.io/name: cluster-health-analyzer-mcp
