kind: Kueue
apiVersion: kueue.openshift.io/v1
metadata:
  name: cluster
  namespace: openshift-kueue-operator
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  config:
    integrations:
      frameworks:
        - BatchJob
  managementState: Managed
