apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: flan-t5-base
  namespace: models
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      storageUri: pvc://hf-pvc/flan-t5-base
