apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: flan-t5-base
  namespace: models
spec:
  predictor:
    model:
      runtime: hf-mlserver-runtime
      modelFormat:
        name: pytorch
      storageUri: pvc://hf-pvc/flan-t5-base
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "8Gi"
