apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: models
resources:
  - namespace.yaml
  - pvc.yaml
  - inferenceservice.yaml
  - servingruntime-hf.yaml   # uncomment only if you DON'T already have a HuggingFace ServingRuntime
