apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-pvc
  namespace: models
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce     # EBS supports RWO only
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem      # 👈 keep filesystem mode
  storageClassName: gp3-csi   # check with oc get sc
