apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-pvc
  namespace: models
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
