apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: hf-mlserver-runtime
  namespace: models
spec:
  supportedModelFormats:
    - name: pytorch
      version: "1"
      autoSelect: true
  containers:
    - name: kserve-container
      image: seldonio/mlserver:1.4.0
      args:
        - --model-store=/mnt/models
      env:
        - name: MLSERVER_MODELS_DIR
          value: /mnt/models
      volumeMounts:
        - name: model-storage
          mountPath: /mnt/models
  volumes:
    - name: model-storage
      persistentVolumeClaim:
        claimName: hf-pvc
