apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: hf-transformers-runtime
  namespace: models
spec:
  supportedModelFormats:
    - name: transformers
      version: "1"
      autoSelect: true
  containers:
    - name: hf-transformers
      image: quay.io/sureshgaikwad/hf-runtime:latest
      args:
        - --model_name={{.Name}}
        - --model_dir=/mnt/models
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
        limits:
          cpu: "2"
          memory: 4Gi
