
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: huggingface-mlserver
  namespace: models
spec:
  supportedModelFormats:
    - name: huggingface
      version: "*"
      autoSelect: true
  containers:
    - name: kserve-container
      image: seldonio/mlserver:1.3.5
      command: ["/opt/mlserver/mlserver"]
      args: ["start"]
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "4"
          memory: "8Gi"
      volumeMounts:
        - name: model-pvc
          mountPath: /mnt/models
  volumes:
    - name: model-pvc
      persistentVolumeClaim:
        claimName: hf-pvc
