apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: phi-3-mini-chat
  namespace: models
  annotations:
    openshift.io/display-name: phi-3-mini-chat
    serving.kserve.io/deploymentMode: RawDeployment
    security.opendatahub.io/enable-auth: "false"
    networking.kserve.io/visibility: exposed
    argocd.argoproj.io/sync-wave: "1"
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "2"
          memory: 6Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
      runtime: vllm-cuda-runtime-phi3
      storageUri: hf://microsoft/Phi-3-mini-128k-instruct
      args:
        - --max-model-len
        - "8192"
        - --gpu-memory-utilization
        - "0.90"
        - --max-num-seqs
        - "2"
