---
apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
  namespace: demo-project
  labels:
    app.kubernetes.io/name: developer-hub
    app.kubernetes.io/component: backstage
    app.kubernetes.io/part-of: developer-hub-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  application:
    # App configuration from ConfigMap
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: developer-hub-app-config
    # Dynamic plugins configuration
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    # Authentication secrets
    extraEnvs:
      secrets:
        - name: developer-hub-auth-secrets
    # User entities file
    extraFiles:
      mountPath: /opt/app-root/src
      configMaps:
        - name: backstage-user-entities
          key: user-entities.yaml
    # Number of replicas (keep at 1 to avoid migration lock issues)
    replicas: 1
    # Enable route
    route:
      enabled: true
      # Custom host can be specified if needed (commented out to use default)
      # host: backstage-developer-hub-demo-project.{{CLUSTER_DOMAIN}}
   #   tls:
   #     enabled: true
   #     termination: edge
   #     insecureEdgeTerminationPolicy: Redirect
  # Database configuration
  database:
    # Use local PostgreSQL database
    enableLocalDb: true
    # For production, use external PostgreSQL:
    # enableLocalDb: false
    # passwordSecret:
    #   name: postgres-secret
    #   key: password
  # Extra environment variables
      # Optional: Disable TLS verification (e.g., when working with self-signed certificates)
      # Uncomment if needed for development with self-signed certs
      # - name: NODE_TLS_REJECT_UNAUTHORIZED
      #   value: '0'
  # Deployment patches for optimization
  deployment:
    patch:
      spec:
        replicas: 1
        template:
          spec:
            # Add volume for dynamic plugins caching (best practice from training exercises)
            # This speeds up startup of dynamic plugins by caching installations
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
