---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-plugins-rhdh
  namespace: demo-project
  labels:
    app.kubernetes.io/name: developer-hub
    app.kubernetes.io/component: dynamic-plugins
    app.kubernetes.io/part-of: developer-hub-stack
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      # ArgoCD Plugin - Backend
      - package: '@roadiehq/backstage-plugin-argo-cd-backend-dynamic@2.13.0'
        disabled: false
      
      # ArgoCD Plugin - Frontend
      - package: '@roadiehq/backstage-plugin-argo-cd@2.10.2'
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              roadiehq.backstage-plugin-argo-cd:
                appIcons:
                  - name: argocdIcon
                    module: ArgocdIcon
                dynamicRoutes:
                  - path: /argo-cd
                    importName: ArgocdPage
                    menuItem:
                      icon: argocdIcon
                      text: ArgoCD
      
      # Tekton Plugin
      - package: './dynamic-plugins/dist/janus-idp-backstage-plugin-tekton'
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              janus-idp.backstage-plugin-tekton:
                appIcons:
                  - name: tektonIcon
                    module: TektonIcon
                dynamicRoutes:
                  - path: /tekton
                    importName: TektonPage
                    menuItem:
                      icon: tektonIcon
                      text: Tekton CI
      
      # Kubernetes Plugin - Backend
      - package: './dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic'
        disabled: false
      
      # Kubernetes Plugin - Frontend
      - package: './dynamic-plugins/dist/backstage-plugin-kubernetes'
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-kubernetes:
                dynamicRoutes:
                  - path: /kubernetes
                    importName: KubernetesPage
                    menuItem:
                      icon: kubernetes
                      text: Kubernetes

