apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-model
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sureshgaikwad/gitops-catalog.git   # your GitOps repo
    targetRevision: main
    path: ai-models/flan-t5-base
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
