apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: datasciencecluster.opendatahub.io
      kind: DataScienceCluster
      name: default-dsc
    patch: |-
      - op: replace
        path: /spec/components/ogx/managementState
        value: Managed
      - op: replace
        path: /spec/components/llamastackoperator/managementState
        value: Removed
      - op: replace
        path: /spec/components/trustyai/managementState
        value: Managed
