apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen-25-7b
  namespace: models
  annotations:
    openshift.io/display-name: qwen-2.5-7b-instruct
    serving.kserve.io/deploymentMode: RawDeployment
    security.opendatahub.io/enable-auth: "false"
    networking.kserve.io/visibility: exposed
    argocd.argoproj.io/sync-wave: "1"
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    tolerations:
      - key: nvidia.com/gpu
        operator: Equal
        value: "true"
        effect: NoSchedule
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 12Gi
          nvidia.com/gpu: "1"
      runtime: vllm-cuda-runtime-qwen
      storageUri: hf://Qwen/Qwen2.5-7B-Instruct
      args:
        - --max-model-len
        - "20000"
        - --gpu-memory-utilization
        - "0.90"
