---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: myrealm-import
  namespace: rhbk
  labels:
    app: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  keycloakCRName: sample-kc
  realm:
    id: myrealm
    realm: myrealm
    enabled: true
    displayName: "My Realm"
    sslRequired: external
    registrationAllowed: false
    loginWithEmailAllowed: true
    duplicateEmailsAllowed: false
    resetPasswordAllowed: true
    editUsernameAllowed: false
    bruteForceProtected: true
    # Users - replace with your actual users
    users:
      - username: "myuser"
        email: "test@gmail.com"
        firstName: "Test"
        lastName: "User"
        enabled: true
        emailVerified: true
        credentials:
          - type: "password"
            value: "redhat"
            temporary: false
    # Client will be defined separately for better management

