---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: myrealm-client-import
  namespace: rhbk
  labels:
    app: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  keycloakCRName: sample-kc
  realm:
    id: myrealm
    realm: myrealm
    clients:
      - clientId: myclient
        name: "Developer Hub Client"
        description: "OIDC client for Red Hat Developer Hub authentication"
        enabled: true
        clientAuthenticatorType: client-secret
        secret: "Zu889CpIBEokBlqDDZuVOs46OQFqGjquNLnV0MRtskE="
        # Protocol settings
        protocol: openid-connect
        publicClient: false
        bearerOnly: false
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: false
        serviceAccountsEnabled: false
        # OAuth settings
        consentRequired: false
        fullScopeAllowed: true
        # URLs - Dynamically generated based on cluster domain
        rootUrl: "https://backstage-developer-hub-demo-project.apps.rosa.sgaikwad.nepj.p3.openshiftapps.com"
        baseUrl: "https://backstage-developer-hub-demo-project.apps.rosa.sgaikwad.nepj.p3.openshiftapps.com"
        redirectUris:
          - "https://backstage-developer-hub-demo-project.apps.rosa.sgaikwad.nepj.p3.openshiftapps.com/api/auth/oidc/handler/frame"
          - "https://backstage-developer-hub-demo-project.apps.rosa.sgaikwad.nepj.p3.openshiftapps.com/api/auth/oidc/handler/frame/*"
          - "https://backstage-developer-hub-demo-project.apps.rosa.sgaikwad.nepj.p3.openshiftapps.com/*"
        webOrigins:
          - "https://backstage-developer-hub-demo-project.apps.rosa.sgaikwad.nepj.p3.openshiftapps.com"
          - "*"
        # Default client scopes
        defaultClientScopes:
          - "openid"
          - "email"
          - "profile"
          - "roles"
          - "web-origins"
        optionalClientScopes:
          - "address"
          - "phone"
          - "offline_access"
        # Protocol mappers for additional claims
        protocolMappers:
          - name: "email"
            protocol: "openid-connect"
            protocolMapper: "oidc-usermodel-property-mapper"
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: "email"
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: "email"
              jsonType.label: "String"
          - name: "preferred_username"
            protocol: "openid-connect"
            protocolMapper: "oidc-usermodel-property-mapper"
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: "username"
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: "preferred_username"
              jsonType.label: "String"
          - name: "groups"
            protocol: "openid-connect"
            protocolMapper: "oidc-group-membership-mapper"
            consentRequired: false
            config:
              full.path: "false"
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: "groups"
              userinfo.token.claim: "true"

