apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: rhbk
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  username: keycloak
  password: keycloak
  database: keycloak

