---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: sample-kc
  namespace: rhbk
  labels:
    app: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: keycloak-server
    app.kubernetes.io/part-of: developer-hub-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1
  hostname:
    strict: false
  http:
    httpEnabled: true
  ingress:
    enabled: true
  proxy:
    headers: xforwarded
  db:
    vendor: postgres
    host: postgres-db
    port: 5432
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  unsupported:
    podTemplate:
      spec:
        containers:
          - env:
              - name: KC_HEALTH_ENABLED
                value: "true"
              - name: KC_METRICS_ENABLED
                value: "true"
              - name: KC_FEATURES
                value: "token-exchange"
              - name: KC_TRANSACTION_XA_ENABLED
                value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: rhbk
  labels:
    app: postgres-db
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-db
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: rhbk
  labels:
    app: postgres-db
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceName: postgres-db
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: testuser
            - name: POSTGRES_PASSWORD
              value: testpassword
            - name: POSTGRES_DB
              value: keycloak
            - name: PGDATA
              value: /data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: rhbk
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  username: testuser
  password: testpassword

