---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhdh
  namespace: openshift-operators
  labels:
    app.kubernetes.io/name: rhdh-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: developer-hub-stack
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: fast
  installPlanApproval: Automatic
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
