---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developer-hub-namespaces
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: namespaces
    app.kubernetes.io/part-of: developer-hub-stack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR-ORG/gitops-devhub.git  # UPDATE THIS!
    targetRevision: main
    path: base/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

