---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developer-hub-operators
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: operators
    app.kubernetes.io/part-of: developer-hub-stack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR-ORG/gitops-devhub.git  # UPDATE THIS!
    targetRevision: main
    path: base/operators
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false  # Don't auto-prune operators
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Wait for operators to be ready before syncing dependent apps
  ignoreDifferences:
    - group: operators.coreos.com
      kind: Subscription
      jsonPointers:
        - /status

